version: "2.2"

services:
  elasticsearch:
    image: wison/elasticsearch-with-hanlp:5.4.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: wison/elasticsearch-with-hanlp:5.4.3
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.3
    container_name: kibana
    environment:
      - 'elasticsearch.url=http://elasticsearch:9200'
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
    name: esdata1
  esdata2:
    driver: local
    name: esdata1

networks:
  esnet: 
